### PR TITLE
add RDP Connections List

### PR DESCRIPTION
**Pull request by rpl**
- move into the InspectorService all the code which track the debugging client connections, the related toolbox (for tabs' developer toolbox and WebIDE toolboxes)  
- introduces a new window for the RDP Connections List React UI
- support to multiple RDP Inspector window concurrently opened
- move some of the helper modules in the **data/shared** dir
- introduce a ReactLazyFactory helper (used to lazily create React factories from the React Component classes, e.g. React Bootstrap components) 

NOTE: a temporary fix is introduced to fix issues on travis with the old firebug.sdk release on nightly

### CODE REVIEW

**Comment by janodvarko** [comment]
Sorry for the delay!

I am seeing the following exception:

Dispatcher.emit; EXCEPTION [Exception... "Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsIXPCComponents_Utils.cloneInto]"  nsresult: "0x80004005 (NS_ERROR_FAILURE)"  location: "JS frame :: resource://gre/modules/commonjs/toolkit/loader.js -> resource://rdpinspector-at-getfirebug-dot-com/lib/connections-list-window.js :: onRDPConnectionsUpdated :: line 158"  data: no] Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsIXPCComponents_Utils.cloneInto]

Honza

**Comment by janodvarko** [comment]
Great work Luka!

My Comments:
1) Localization isn't fully supported. All UI strings should be in a *.properties file. You might want to create a new on e.g. connection-list.properties, I'll leave this up to you.
2) The temp fix for FBSDK can be removed I guess (FBSDK published yesterday)
3) The ReactLazyFactory looks good, it could be moved to FBSDK I guess
4) The 'Monitor WebIDE Connections' option should be removed
5) Rename 'RDP Connections List Selector' to 'Connect To ...' The menu item should also be enclosed by two menu-separators (above and below)
6) Nit: 'ConnectionsList'  should be rather 'ConnectionList' - I think that the plural isn't necessary since there is the 'List' postfix alrady (related also to the dir name). I'll leave this up to you.
7) Why 'ToolboxOverlay' isn't property registered in main.js anymore? It's now manually instantiated in inspector-service.js. I think it's wrong. Not sure what was the reason, but Perhaps we also need to introduce WebIDEOverlay() in FBSDK (to follow life cycle of WebIDE)?
8) The pull needs to be rebased on the master (module path changes)

Honza

**Comment by rpl** [comment]
- [X] pull request rebased on the new master (module path changes)
- [X] remove FBSDK temporary fix for tavis (excluded from the rebased branch)
- [X] externalize new strings to locales (28d8b57)
- [X] "Monitor WebIDE Connections" preference removed, it now always monitor webide connections ( 0045e9a)
- [X] "Auto open RDP Inspector on WebIDE Connections" preference added, off by default ( 0045e9a)
- [X] rename 'RDP Connections List Selector' to 'Connect To...' (28d8b57)
- [X] put 'Connect to...' inside two menu item separators (d56b6aa)

Next steps:
- [ ] rename 'ConnectionsList' to 'ConnectionList'
- [ ] find a better solution for the ToolboxOverlay

**Comment by rpl** [comment]
@janodvarko I've just pushed the new proposal solution (in d821973 and it only needs a small change on the FBSDK side, which I pushed on the PR firebug/firebug.sdk#13):

it leaves the creation of the ToolboxOverlay to the FBSDK and it is able to get a reference to the instance created for a defined toolbox by receiving it from the Dispatcher.

**Comment by janodvarko** [comment]
Tested and works great to me, thanks!

Honza

**Pull request merged**
