### PR TITLE
rdp packet editor

### LINKED ISSUE #6: Packet editor side bar
It should be possible to send packet to the backend.
(see also: https://github.com/firebug/firebug.next/pull/375)

From the pull:
1. The editor UX should be similar to what we have done in Firebug 2 for the Watch panel. See wiki: https://getfirebug.com/wiki/index.php/Watch_Side_Panel The panel shows how rows should be edited/appended/removed

2. A "type" field can automatically offer (auto-complete) options from ObjectActor.requestTypes (ideally: request fields like actor id, etc. are filled in automatically)

Honza

### PR DESCRIPTION
**Pull request by rpl**
This branch re-introduce a rewrite (and UI restyle) of the previous packet editor sidebar (and fix #6)

Dependencies:

- firebug/firebug.sdk#7
- #17 

NOTE: it's currently based on the PR #17 so it can't be merged as it is until #17 will be merged (or reverted from this branch).

rdpinspector_packeteditor

### CODE REVIEW

**Comment by rpl** [comment]
@janodvarko I'm going to rebase #17 and #18 on the new master, sorry for the multiple rebases of #17 related to its included react modules rename.

**Comment by rpl** [comment]
just pushed refreshed rebase on master for #17 and #18

**Comment by janodvarko** [comment]
Excellent progress!

See my comments:

1. Do not indent code code inside modules (i.e. inside the define function).
2. Use /** @lends <object-name> */ directive for JS docs. See e.g. packet-store.js file for an example. 
3. We don't use console.log, but FBTrace.sysout

Editing:
1.  When strings are edited, quotes shouldn't be displayed and required. If set by the user they should be escaped.
2. It should be possible to end edit mode by clicking outside of the editor. Currently only Enter key is supported.
3. Start editing should be done by clicking anywhere in memberValueCell, currently the user needs to click the value. (editing label works fine)
4. Is it possible to create packet sub-properties? It's tree, right?
5. The content of the Editor is often auto-cleared. It looks like it's somehow connected to selection changes. This should never happen since it takes time and effort to fill in the right props. Packet selection changes should have no impact on the editor. Later we can add helper context menu actions like "Copy Packet to Editor" 

More stuff:
This shouldn't be probably part of this issue, but. I'd like to have some helper UI for picking the target actor ID - the "to" field. E.g. there should be another "..." (three dots) icon next to the 'remove' icon (or rather before it) opening a popup that displays ID of all global actors and IDs of all tab actors (for the current tab). It could be one big list with two sections. The UI should allow to pick one ID and copy it into the "to: " field. The "type" field should have similar button also opening the popup, but filled with allowed types for the currently selected actor ID. Packets sent by RDP Inspector itself should be hidden.

We should discuss UX details on our Firebug meeting tomorrow.

I am merging this in, to avoid conflicts, but please see my comments.

Great stuff

Honza

**Comment by janodvarko** [comment]
@rpl Btw. what time zone are you based in?

Honza

**Comment by janodvarko** [comment]
> 1. When strings are edited, quotes shouldn't be displayed and required. If set by the user they
> should be escaped.

This might be more complicated. The use might want to create a bool prop by typing true (no quotes) or string prop by typing "true" (with quotes)....

Honza

**Comment by rpl** [comment]
@janodvarko copy that! I'm going to work on the cleanup and fix tasks from your previous comments first, and than I'll start to prototype the advanced features (e.g. autocompletion was already in my roadmap and I've already a couple of ideas on where and how to hook it, but I wanted to get this to work as before first so we had been able to remove the old version from firebug.next)

**Comment by rpl** [comment]
@janodvarko I should be able to join the Firebug meeting today

I'm in based in the UTC+1 timezone (Rome)

**Comment by janodvarko** [comment]
> I should be able to join the Firebug meeting today

Great

> I'm based in the UTC+1 timezone (Rome) 

Good, we are close (I am UTC+2)

Honza

**Pull request merged**
