### PR TITLE
Testing: test unit React Components using karma and jasmine

### PR DESCRIPTION
**Pull request by rpl**
This pull request introduces a "content side" test suite to test unit React Components used in most of the addon UI (to be run on travis side by side with the jpm test suite which will test the privileged code).

- add a karma configuration: jasmine + requirejs
- inject mocks to polyfill missing globals injected by the privileged code
- prototype first batch of React components specs (main-tabbed-panel-Spec.js and packets-panel-Spec.js)  
- integrate travis-ci config
- run vebose spec output during travis-ci build
- define custom React oriented matchers for jasmine

Example Build: https://travis-ci.org/rpl/rdp-inspector/builds/62235398

- optional autoWatch & code coverage mode:
```
CODE_COVERAGE=true FIREFOX_BIN=/opt/firefox-nightly/firefox npm run watch-karma-tests
```

rdp-inspector-coverage_0
rdp-inspector-coverage_1

### CODE REVIEW

**Comment by janodvarko** [comment]
This is great contribution Luca!

Some comments:

* Some files are using capitalized letters (e.g. actors-panel-Spec) they should not
* Content of packets-panel-Spec.js and main-tabbed-area-Spec.js should use the same tab style as other existing modules (i.e. do not intend the entire module with one tab) Btw. shouldn't the name of the file be rather main-tabbed-area-suite.js? (containing suite of specs...) Btw. the TEST_REGEXP (in test-main) would have to change too.
* I think we don't want to have karma-test directory included in the result xpi. The .jpmignore file should be updated.
* The coverage dir should also be excluded from building the xpi
* RE: console.log("UNKOWN Option.getPref: ", key);
Shouldn't we rather throw an exception when unknown pref is required?
* This is more of a question, I am seeing this comment in "karma-tests/test-main.js" Karma serves files under /base, which is the basePath from your config file
Where is the 'base' directory specified?
* Nit: The following constructs:

      [
        PacketsPanelComponent,
        ActorsPanelComponent
      ].forEach((Component) => {
        expect(Component).toBeFoundInReactTree(theApp, 1);
      });

Can we change it to something like:
      var componentes = [PacketsPanelComponent, ActorsPanelComponent];
      componentes.forEach(component => {
        expect(component).toBeFoundInReactTree(theApp, 1);
      });

* I have also reported https://github.com/firebug/rdp-inspector/issues/36
This can be refactored later as a follow up.

Honza

**Comment by janodvarko** [comment]
Btw. why not using Jest?
https://facebook.github.io/jest/
Honza

**Comment by rpl** [comment]
@janodvarko I've just pushed a bunch of commits which address most of the above comments:

> - Some files are using capitalized letters (e.g. actors-panel-Spec) they should not
> - Content of packets-panel-Spec.js and main-tabbed-area-Spec.js should use the same tab style as other existing modules (i.e. do not intend the entire module with one tab) 
> - Nit: Rewrite the array iteration constructs in the existing specs

done in ef2acfc and ebb9d18

> - I think we don't want to have karma-test directory included in the result xpi. The .jpmignore file should be updated.
> - The coverage dir should also be excluded from building the xpi

done in 63ceebe

> - RE: console.log("UNKOWN Option.getPref: ", key); Shouldn't we rather throw an exception when unknown pref is required?

done in 971c3e0 

> - Btw. shouldn't the name of the file be rather main-tabbed-area-suite.js? (containing suite of specs...)

I preferred to leave the *-spec.js (in lowercase) because it's one of the default suffixes suggested in the karma docs, but I'm not against renaming them to *-suite.js.  

> - This is more of a question, I am seeing this comment in "karma-tests/test-main.js" Karma serves files under /base, which is the basePath from your config file Where is the 'base' directory specified?
> - Btw. why not using Jest? https://facebook.github.io/jest/

Let me elaborate on these two, I've two main concerns about how well Jest fits in our scenario:

- Jest hooks itself into the nodejs loader (to mock automatically the loaded modules) and this doesn't play well with the loader we're currently using, requirejs (or at least Jest doesn't support requirejs without hacky workarounds)

- Jest runs unit tests on React components on nodejs and jsdom, and this doesn't fit with our use of ES6 syntaxes supported by spidermonkey, as they can be unsupported on nodejs (without --harmony options and/or a transpiler like babel or traceur) or they can works differently (rare but still possible)

Jest is a very opinionated tool and it doesn't have any plugin or config file, so I looked around for the alternatives approaches and decided to take a look at karma. 

karma, on the contrary, is very configurable, it has an official requirejs plugin and it runs the unit tests on real browsers (so we are sure we are testing the ES6 code on a defined version of the Firefox JS engine)

once karma is configured, it works on a very simple principle:

every browser connected to its server will concurrently run the unit tests on every "karma run" request (launcher modules, like karma-firefox-launcher, just automate the process of opening a browser on the correct http url)

the "/base/" prefix is the path where the unit tests assets are served, because karma serves the test runner page on its default url  (which connects the browser to the karma server, runs the unit tests and sends the results back to the karma server)

**Comment by janodvarko** [comment]
Looks good, thanks!

Honza

**Pull request merged**
